version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"

  apache:
    image: httpd:latest
    container_name: httpd
    ports:
      - "8082:80"