version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - "./test/volume:/usr/share/nginx/html/"

  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "8082:80"
    volumes:
      - "./test/volume:/usr/local/apache2/htdocs/"
